### ISSUE TITLE
add geometry shader reflections

### ISSUE THREAD

**Issue by OmarHadhoud** [MoustaphaSaad/sabre#19]
currently, sabre doesn't reflect geometry shader, it is needed to reflect the geometry shader as it can has uniforms that are needed

to reproduce this issue, run the following command `./build/bin/debug/sabrec.exe reflect ./unittest/data/codegen-shader/simple_geometry.sabre -entry main` 

the problem is in file reflect.cpp, line 52, I think it should be:
```
case COMPILATION_MODE_VERTEX:
case COMPILATION_MODE_PIXEL:
case COMPILATION_MODE_GEOMETRY:
    _generate_entry_shader_io(unit, compilation_unit->entry_symbol);
    break;
default:
    assert(false && "unreachable");
    break;
```

**Comment by MoustaphaSaad** [comment]
fixed in ae587a839b116a290cd62a27cf03fc85527385db
