### ISSUE TITLE
Infinite loop possibility in the generated glsl shader when using continue inside for loop

### ISSUE THREAD

**Issue by WaleedSymbyo** [MoustaphaSaad/sabre#30]
Having a for loop similar to this in sabre
```
for var i = 0; i < 10; i++ {
	if i == 0 {
		continue;
	}
}
```
will be converted to something like that in glsl
```
int i = 0;
while (i < 10)
{
	if (i == 0)
	{
		continue;
	}
	i += 1;
}
```
Which will cause infinite loop as the increment part will never be called once we call `continue`.

**Comment by MoustaphaSaad** [comment]
fixed in #32
