### ISSUE TITLE
floating-point literals that doesn't start with a number causes a crash

### ISSUE THREAD

**Issue by WaleedSymbyo** [MoustaphaSaad/sabre#33]
Having a code like that
```
var x = .1;
```
instead of
```
var x = 0.1;
```
or
```
var x: float;
if x > .5 {
...
}
```
instead of
```
if x > 0.5 {
...
}
```
Causes a crash without giving a useful error message with is very hard to debug. I think Sabre should either support this kind of literal or give a useful error message to the user.
Here is my use case
![image](https://user-images.githubusercontent.com/42381644/146676776-107ab793-f5f0-421f-92ff-cdb2ee532637.png)

I also tried it in the unit tests of sabre and I get segmentation fault
![image](https://user-images.githubusercontent.com/42381644/146676886-069cd070-b5e4-485d-acfc-a3774caab836.png)

**Comment by MoustaphaSaad** [comment]
Fixed in #31
